audit_header: false
title: Bay Area Real Estate Video Blog with Sharad Gupta
description: Our mission at Keller Williams Realty Cupertino is to be your best resource for Bay Area real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Keller Williams Realty Cupertino, your professional Bay Area Real Estate Agents.
show_custom_links: true
custom_links:
  - title: COVID-19 Selling Plan
    url: https://www.sanjosehothomedeals.com/covid-19_seller_protection_plan
  - title: Testimonials
    url:  
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Sharad Gupta
  title:
  license_number:
  about_markdown: |
    Real Estate Sales Team with over 15 years of diversified experience in real estate sales, property development, and business consulting. With a keen eye to spot real estate opportunities and natural aptitude for building trusted business partnerships, we have helped hundreds of families build Real Estate Wealth.

    When you list your home with us, Your Home is Sold Guaranteed or We'll Buy It. Your home will sell for more money, in less time and for the least amount of hassle. We sell 48% more homes than any other average real estate agent in the area. Our homes sell for an average of 7.3% higher than list price and in 14.2% less time than average. We Beat Every Redfin Rebate. If you do not like the home you purchase through us and in the next 6 months, we will either buy it back or sell it back in the market for zero cost to you. Our Service is Guaranteed and there are no fixed contracts. If you do not like our services at any time, you can fire us. No questions asked. Zero Risk and No Obligation. Call Now & Start Your Packing. No Hassle. No Gimmicks. Check out our Reviews. Some conditions apply.

  brand: Keller Williams Realty Cupertino
  brokerage:
  market: Bay Area
  address: 19400 Stevens Creek Blvd, Suite#200, Cupertino CA 95014
  phone: 408-763-8133
  phone_type:
  phone2:
  phone2_type:
  email: contact@sharadgupta.realtor
  url: http://www.bayareahothomedeals.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.bayareahothomedeals.com/homeeval
  second_CTA_text: Home Search
  second_CTA_URL: http://www.bayareahothomedeals.com/Listings/Search/1

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Bay Area Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.bayareahothomedeals.com/homeeval

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Bay Area Home?"
    CTA_text2: "Search the entire MLS for your Bay Area home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.bayareahothomedeals.com/Listings/Search/1

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
  google_reviews_url: https://www.google.com/search?q=sharad+gupta+realtor&oq=sharad+gupta+realtor&aqs=chrome.0.69i59.5263j0j7&sourceid=chrome&ie=UTF-8

podcast:
  title: 'Bay Area Real Estate Podcast with Sharad Gupta'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Bay Area Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams Realty Cupertino - your professional Bay Area Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Bay Area, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Sharad Gupta'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_logo_path2: /img/logo2.png
  logo_width_number: 60
  hero_text: We Don't Sell Homes, We Change Lives
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
